### ISSUE TITLE
Request: Add electron-bitnet

### ISSUE THREAD

**Issue by grctest** [HuangOwen/Awesome-LLM-Compression#31]
I've been working on [Electron-BitNet](https://github.com/grctest/Electron-BitNet) recently, it's an UI for assisting Microsoft's BitNet 1-bit LLM research/usage.

I'd appreciate it if you added it to your awesome list, thanks :)

**Comment by HuangOwen** [comment]
Thanks for your great work! I have appended [Electron-BitNet](https://github.com/grctest/Electron-BitNet) to the list of tools.
