### ISSUE TITLE
Request: Add FastAPI-BitNet

### ISSUE THREAD

**Issue by grctest** [HuangOwen/Awesome-LLM-Compression#35]
I've been working on another project relating to Microsoft's BitNet recently: https://github.com/grctest/FastAPI-BitNet

It uses [Uvicorn](https://www.uvicorn.org/) + [FastAPI](https://fastapi.tiangolo.com/) (Python) and [Docker](https://www.docker.com/) to provide a reliable REST API for testing BitNet out locally!

It supports running the inference framework, running bitnet model benchmarks and calculating bitnet model perplexity values.

It's offers the same functionality as the Electron-BitNet project, however it does so through a REST API which devs/researchers can use to automate testing/benchmarking of BitNet models.

Thanks :)

**Comment by HuangOwen** [comment]
Thanks for your great work! I have appended your repo in the tools section.
