### ISSUE TITLE
Request: add kvpress

### ISSUE THREAD

**Issue by SimJeg** [HuangOwen/Awesome-LLM-Compression#36]
Hello, 

Would it be possible to add https://github.com/NVIDIA/kvpress in the list of tools ? 
Thanks for your awesome repo !

**Comment by HuangOwen** [comment]
Sure, I have appended kvpress to the list of tools. Thanks for your interest in our repo!

**Comment by SimJeg** [comment]
Thanks ! We added a reference to Awesome-LLM-Compression in the README

**Comment by brisker** [comment]
@HuangOwen 
Minor advice: the papers can be sorted by date, so that we can read them and get the latest information more conveniently.

**Comment by HuangOwen** [comment]
> [@HuangOwen](https://github.com/HuangOwen) Minor advice: the papers can be sorted by date, so that we can read them and get the latest information more conveniently.

Thanks for your advice! Currently, all the papers are already sorted by date, with the latest work at the bottom. I am considering a better way to list them. Stay tuned!
